[versions]
gradle = "7.4.2"
kotlin = "1.5.31"
dokka = "1.5.31"

jvmTarget = "1.8"

[libraries]
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.10.1" }
junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-plugin = { module = "com.android.tools.build:gradle", version = "7.2.0" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
versions = { id = "com.github.ben-manes.versions", version = "0.42.0" }
pluginPublish = { id = "com.gradle.plugin-publish", version = "0.18.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.14.2" }
